workflow:
on:
  - push
  - workflow_dispatch
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying code" 