name: workflow
on:
  - push
  - workflow_dispatch
jobs:

  test:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.publish.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test
      
      #output publish
      - name: output
        id: publish
        run: echo 'name="Phani"' >> $GITHUB_OUTPUT
      

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying code" 